{% set version = "13.1.0" %}

package:
  name: cuda-libraries-dev
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  skip: true  # [osx or ppc64le]

requirements:
  run:
    - cuda-cudart-dev 13.1.80
    - cuda-cccl_{{ target_platform }} 13.1.78
    - cuda-profiler-api 13.1.80
    - cuda-driver-dev 13.1.80    # [linux]
    - cuda-nvrtc-dev 13.1.80
    - cuda-opencl-dev 13.1.80    # [linux64 or win]
    - libcublas-dev 13.2.0.9
    - libcufft-dev 12.1.0.31
    - libcufile-dev 1.16.0.49       # [linux]
    - libcurand-dev 10.4.1.34
    - libcusolver-dev 12.0.7.41
    - libcusparse-dev 12.7.2.19
    - libnpp-dev 13.0.2.21
    - libnvfatbin-dev 13.1.80
    - libnvjitlink-dev 13.1.80
    - libnvjpeg-dev 13.0.2.28

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library development packages.
  description: |
    Meta-package containing all available library development packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
