{% set version = "13.0.2" %}

package:
  name: cuda-libraries-dev
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  skip: true  # [osx or ppc64le]

requirements:
  run:
    - cuda-cudart-dev 13.0.96
    - cuda-cccl_{{ target_platform }} 13.0.85
    - cuda-profiler-api 13.0.85
    - cuda-driver-dev 13.0.96    # [linux]
    - cuda-nvrtc-dev 13.0.88
    - cuda-opencl-dev 13.0.85    # [linux64 or win]
    - libcublas-dev 13.1.0.3
    - libcufft-dev 12.0.0.61
    - libcufile-dev 1.15.1.6       # [linux]
    - libcurand-dev 10.4.0.35
    - libcusolver-dev 12.0.4.66
    - libcusparse-dev 12.6.3.3
    - libnpp-dev 13.0.1.2
    - libnvfatbin-dev 13.0.85
    - libnvjitlink-dev 13.0.88
    - libnvjpeg-dev 13.0.1.86

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library development packages.
  description: |
    Meta-package containing all available library development packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
